version: '3'

services:
  postgres:
    container_name: 'postgres-dev'
    image: postgres:latest
    restart: always
    volumes: 
      - ./data/postgres:/data/postgres
    ports: 
      - '5432:5432'
    env_file:
      - docker.dev.env
    networks:
      - app-tier
  
  app:
    container_name: 'app-dev'
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '3001:3001'
    depends_on:
      - postgres
    volumes: 
      - ./src:/app/src
    networks:
      - app-tier
    restart: always
  
  pgadmin4:
    container_name: 'pgadmin4-dev'
    image: dpage/pgadmin4:latest
    ports: 
      - '5050:80'
    env_file:
      - docker.dev.env
    networks:
      - app-tier
    restart: always
    depends_on:
      - postgres

networks:
  app-tier:
    driver: bridge
