import { Template } from '@pdfme/common';

const template: Template = {
  schemas: [
    {
      logo: {
        type: 'readOnlyImage',
        position: { x: 20, y: 20 },
        width: 30,
        height: 30,
        rotate: 0,
        opacity: 1,
        readOnly: true,
      },
      modelName: {
        type: 'readOnlyText',
        position: { x: 92.09, y: 20 },
        content: 'Model name',
        width: 97.91,
        height: 9.98,
        rotate: 0,
        alignment: 'left',
        verticalAlignment: 'middle',
        fontSize: 20,
        lineHeight: 1,
        characterSpacing: 0,
        fontColor: '#000000',
        backgroundColor: '',
        opacity: 1,
        readOnly: true,
        fontName: 'NotoSerifJP-Regular',
      },
      offerFromDate: {
        type: 'readOnlyText',
        position: { x: 92.09, y: 30.21 },
        content: 'Offer from date',
        width: 97.91,
        height: 9.98,
        rotate: 0,
        alignment: 'left',
        verticalAlignment: 'middle',
        fontSize: 14,
        lineHeight: 1,
        characterSpacing: 0,
        fontColor: '#000000',
        backgroundColor: '',
        opacity: 1,
        readOnly: true,
        fontName: 'NotoSerifJP-Regular',
      },
      offerNumber: {
        type: 'readOnlyText',
        position: { x: 92.09, y: 40.79 },
        content: 'Offer number',
        width: 97.91,
        height: 9.98,
        rotate: 0,
        alignment: 'left',
        verticalAlignment: 'middle',
        fontSize: 14,
        lineHeight: 1,
        characterSpacing: 0,
        fontColor: '#000000',
        backgroundColor: '',
        opacity: 1,
        readOnly: true,
        fontName: 'NotoSerifJP-Regular',
      },
      createdForLabel: {
        type: 'readOnlyText',
        position: { x: 20, y: 57.88 },
        content: 'Created for:',
        width: 80,
        height: 9.42,
        rotate: 0,
        alignment: 'left',
        verticalAlignment: 'top',
        fontSize: 13,
        lineHeight: 1,
        characterSpacing: 0,
        fontColor: '#000000',
        backgroundColor: '',
        opacity: 1,
        readOnly: true,
        fontName: 'NotoSerifJP-Regular',
      },
      createdForNameLastName: {
        type: 'text',
        content: 'Name Lastname\n',
        position: { x: 20, y: 67.41 },
        width: 80,
        height: 8.4,
        rotate: 0,
        alignment: 'left',
        verticalAlignment: 'top',
        fontSize: 16,
        lineHeight: 1,
        characterSpacing: 0,
        fontColor: '#000000',
        backgroundColor: '',
        opacity: 1,
        fontName: 'NotoSerifJP-Regular',
      },
      createdForEmail: {
        type: 'text',
        content: 'Email\n',
        position: { x: 20, y: 77.41 },
        width: 80,
        height: 8.4,
        rotate: 0,
        alignment: 'left',
        verticalAlignment: 'top',
        fontSize: 16,
        lineHeight: 1,
        characterSpacing: 0,
        fontColor: '#000000',
        backgroundColor: '',
        opacity: 1,
        fontName: 'NotoSerifJP-Regular',
      },
      oneTimePasswordLabel: {
        type: 'readOnlyText',
        position: { x: 110, y: 57.88 },
        content: 'One-time password:',
        width: 80,
        height: 9.42,
        rotate: 0,
        alignment: 'left',
        verticalAlignment: 'top',
        fontSize: 13,
        lineHeight: 1,
        characterSpacing: 0,
        fontColor: '#000000',
        backgroundColor: '',
        opacity: 1,
        readOnly: true,
        fontName: 'NotoSerifJP-Regular',
      },
      oneTimePasswordContent: {
        type: 'text',
        content: 'Password',
        position: { x: 110, y: 67.41 },
        width: 80,
        height: 8.93,
        rotate: 0,
        alignment: 'left',
        verticalAlignment: 'top',
        fontSize: 16,
        lineHeight: 1,
        characterSpacing: 0,
        fontColor: '#000000',
        backgroundColor: '',
        opacity: 1,
        fontName: 'NotoSerifJP-Regular',
      },
      modelImage: {
        type: 'image',
        position: { x: 20, y: 88.2 },
        width: 169.65,
        height: 72.28,
        rotate: 0,
        opacity: 1,
      },
      baseConfigurationTitle: {
        type: 'readOnlyText',
        icon: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-type"><polyline points="4 7 4 4 20 4 20 7"/><line x1="9" x2="15" y1="20" y2="20"/><line x1="12" x2="12" y1="4" y2="20"/></svg>',
        content: 'Base configuration',
        position: { x: 20, y: 165.79 },
        width: 170,
        height: 10,
        rotate: 0,
        alignment: 'left',
        verticalAlignment: 'top',
        fontSize: 18,
        lineHeight: 1,
        characterSpacing: 0,
        fontColor: '#000000',
        backgroundColor: '',
        opacity: 1,
        readOnly: true,
        fontName: 'NotoSerifJP-Regular',
      },
      baseConfigurationTable: {
        type: 'table',
        position: { x: 20, y: 177.92 },
        width: 170,
        height: 62.1048,
        content: '[["","Item name 1","$123","$123"],["","","",""]]',
        showHead: true,
        head: ['Item image', 'Item name', 'Price', 'Total'],
        headWidthPercentages: [
          27.18538451833581, 40.315771769765846, 19.26354959425127,
          13.23529411764708,
        ],
        fontName: 'NotoSerifJP-Regular',
        tableStyles: { borderWidth: 0, borderColor: '#000000' },
        headStyles: {
          fontName: 'NotoSerifJP-Regular',
          fontSize: 13,
          characterSpacing: 0,
          alignment: 'center',
          verticalAlignment: 'middle',
          lineHeight: 1,
          fontColor: '#2f40d6',
          borderColor: '#2f40d6',
          backgroundColor: '#d7daf7',
          borderWidth: { top: 0.2, right: 0.2, bottom: 0.2, left: 0.2 },
          padding: { top: 5, right: 5, bottom: 5, left: 5 },
        },
        bodyStyles: {
          fontName: 'NotoSerifJP-Regular',
          fontSize: 13,
          characterSpacing: 0,
          alignment: 'center',
          verticalAlignment: 'middle',
          lineHeight: 3,
          fontColor: '#000000',
          borderColor: '#000000',
          backgroundColor: '',
          alternateBackgroundColor: '',
          borderWidth: { top: 0.2, right: 0.2, bottom: 0.2, left: 0.2 },
          padding: { top: 5, right: 5, bottom: 5, left: 5 },
        },
        columnStyles: {
          alignment: {
            '0': 'center',
            '1': 'left',
            '2': 'center',
            '3': 'right',
          },
        },
      },
      itemImage: {
        type: 'readOnlyImage',
        icon: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-image-off"><line x1="2" x2="22" y1="2" y2="22"/><path d="M10.41 10.41a2 2 0 1 1-2.83-2.83"/><line x1="13.5" x2="6" y1="13.5" y2="21"/><line x1="18" x2="21" y1="12" y2="15"/><path d="M3.59 3.59A1.99 1.99 0 0 0 3 5v14a2 2 0 0 0 2 2h14c.55 0 1.052-.22 1.41-.59"/><path d="M21 15V5a2 2 0 0 0-2-2H9"/></svg>',
        content: '',
        position: { x: 32.07, y: 192.57 },
        width: 23.5,
        height: 23.5,
        rotate: 0,
        opacity: 1,
        readOnly: true,
      },
      pageNumber: {
        type: 'readOnlyText',
        icon: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-type"><polyline points="4 7 4 4 20 4 20 7"/><line x1="9" x2="15" y1="20" y2="20"/><line x1="12" x2="12" y1="4" y2="20"/></svg>',
        content: 'Page 1 from 5',
        position: { x: 145, y: 271.23 },
        width: 35,
        height: 5.769999999999982,
        rotate: 0,
        alignment: 'left',
        verticalAlignment: 'bottom',
        fontSize: 12,
        lineHeight: 1,
        characterSpacing: 0,
        fontColor: '#000000',
        backgroundColor: '',
        opacity: 1,
        readOnly: true,
        fontName: 'NotoSerifJP-Regular',
      },
      createdByLabel: {
        type: 'readOnlyText',
        icon: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-type"><polyline points="4 7 4 4 20 4 20 7"/><line x1="9" x2="15" y1="20" y2="20"/><line x1="12" x2="12" y1="4" y2="20"/></svg>',
        content: 'Created by:',
        position: { x: 20, y: 261.97 },
        width: 50,
        height: 7.36,
        rotate: 0,
        alignment: 'left',
        verticalAlignment: 'bottom',
        fontSize: 14,
        lineHeight: 1,
        characterSpacing: 0,
        fontColor: '#000000',
        backgroundColor: '',
        opacity: 1,
        readOnly: true,
        fontName: 'NotoSerifJP-Regular',
      },
      creatorName: {
        type: 'readOnlyText',
        icon: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-type"><polyline points="4 7 4 4 20 4 20 7"/><line x1="9" x2="15" y1="20" y2="20"/><line x1="12" x2="12" y1="4" y2="20"/></svg>',
        content: 'Creator name',
        position: { x: 20, y: 269.64 },
        width: 50,
        height: 7.36,
        rotate: 0,
        alignment: 'left',
        verticalAlignment: 'bottom',
        fontSize: 14,
        lineHeight: 1,
        characterSpacing: 0,
        fontColor: '#000000',
        backgroundColor: '',
        opacity: 1,
        readOnly: true,
        fontName: 'NotoSerifJP-Regular',
      },
    },
    {
      additionalConfigurationTitle: {
        type: 'readOnlyText',
        icon: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-type"><polyline points="4 7 4 4 20 4 20 7"/><line x1="9" x2="15" y1="20" y2="20"/><line x1="12" x2="12" y1="4" y2="20"/></svg>',
        content: 'Additional configuration',
        position: { x: 20, y: 62.82 },
        width: 170,
        height: 10,
        rotate: 0,
        alignment: 'left',
        verticalAlignment: 'top',
        fontSize: 18,
        lineHeight: 1,
        characterSpacing: 0,
        fontColor: '#000000',
        backgroundColor: '',
        opacity: 1,
        readOnly: true,
        fontName: 'NotoSerifJP-Regular',
      },
      additionalConfigurationTable: {
        type: 'table',
        position: { x: 20, y: 74.95 },
        width: 170,
        height: 62.1048,
        content: '[["","Item name 1","$123","$123"],["","","",""]]',
        showHead: true,
        head: ['Item image', 'Item name', 'Price', 'Total'],
        headWidthPercentages: [
          27.18538451833581, 40.315771769765846, 19.26354959425127,
          13.23529411764708,
        ],
        fontName: 'NotoSerifJP-Regular',
        tableStyles: { borderWidth: 0, borderColor: '#000000' },
        headStyles: {
          fontName: 'NotoSerifJP-Regular',
          fontSize: 13,
          characterSpacing: 0,
          alignment: 'center',
          verticalAlignment: 'middle',
          lineHeight: 1,
          fontColor: '#2f40d6',
          borderColor: '#2f40d6',
          backgroundColor: '#d7daf7',
          borderWidth: { top: 0.2, right: 0.2, bottom: 0.2, left: 0.2 },
          padding: { top: 5, right: 5, bottom: 5, left: 5 },
        },
        bodyStyles: {
          fontName: 'NotoSerifJP-Regular',
          fontSize: 13,
          characterSpacing: 0,
          alignment: 'center',
          verticalAlignment: 'middle',
          lineHeight: 3,
          fontColor: '#000000',
          borderColor: '#000000',
          backgroundColor: '',
          alternateBackgroundColor: '',
          borderWidth: { top: 0.2, right: 0.2, bottom: 0.2, left: 0.2 },
          padding: { top: 5, right: 5, bottom: 5, left: 5 },
        },
        columnStyles: {
          alignment: {
            '0': 'center',
            '1': 'left',
            '2': 'center',
            '3': 'right',
          },
        },
      },
      logo: {
        type: 'readOnlyImage',
        position: { x: 20, y: 20.21 },
        icon: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-image-off"><line x1="2" x2="22" y1="2" y2="22"/><path d="M10.41 10.41a2 2 0 1 1-2.83-2.83"/><line x1="13.5" x2="6" y1="13.5" y2="21"/><line x1="18" x2="21" y1="12" y2="15"/><path d="M3.59 3.59A1.99 1.99 0 0 0 3 5v14a2 2 0 0 0 2 2h14c.55 0 1.052-.22 1.41-.59"/><path d="M21 15V5a2 2 0 0 0-2-2H9"/></svg>',
        content: '',
        width: 30,
        height: 30,
        rotate: 0,
        opacity: 1,
        readOnly: true,
      },
      modelName: {
        type: 'readOnlyText',
        position: { x: 92.04, y: 20.21 },
        content: 'Model name',
        width: 97.91,
        height: 9.98,
        rotate: 0,
        alignment: 'left',
        verticalAlignment: 'middle',
        fontSize: 20,
        lineHeight: 1,
        characterSpacing: 0,
        fontColor: '#000000',
        backgroundColor: '',
        opacity: 1,
        readOnly: true,
        fontName: 'NotoSerifJP-Regular',
      },
      offerFromDate: {
        type: 'readOnlyText',
        position: { x: 92.09, y: 30.42 },
        content: 'Offer from date',
        width: 97.91,
        height: 9.98,
        rotate: 0,
        alignment: 'left',
        verticalAlignment: 'middle',
        fontSize: 14,
        lineHeight: 1,
        characterSpacing: 0,
        fontColor: '#000000',
        backgroundColor: '',
        opacity: 1,
        readOnly: true,
        fontName: 'NotoSerifJP-Regular',
      },
      offerNumber: {
        type: 'readOnlyText',
        position: { x: 92.09, y: 41 },
        content: 'Offer number',
        width: 97.91,
        height: 9.98,
        rotate: 0,
        alignment: 'left',
        verticalAlignment: 'middle',
        fontSize: 14,
        lineHeight: 1,
        characterSpacing: 0,
        fontColor: '#000000',
        backgroundColor: '',
        opacity: 1,
        readOnly: true,
        fontName: 'NotoSerifJP-Regular',
      },
      itemImage: {
        type: 'readOnlyImage',
        icon: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-image-off"><line x1="2" x2="22" y1="2" y2="22"/><path d="M10.41 10.41a2 2 0 1 1-2.83-2.83"/><line x1="13.5" x2="6" y1="13.5" y2="21"/><line x1="18" x2="21" y1="12" y2="15"/><path d="M3.59 3.59A1.99 1.99 0 0 0 3 5v14a2 2 0 0 0 2 2h14c.55 0 1.052-.22 1.41-.59"/><path d="M21 15V5a2 2 0 0 0-2-2H9"/></svg>',
        content: '',
        position: { x: 31.69, y: 89.59 },
        width: 23.5,
        height: 23.5,
        rotate: 0,
        opacity: 1,
        readOnly: true,
      },
      createdByLabel: {
        type: 'readOnlyText',
        icon: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-type"><polyline points="4 7 4 4 20 4 20 7"/><line x1="9" x2="15" y1="20" y2="20"/><line x1="12" x2="12" y1="4" y2="20"/></svg>',
        content: 'Created by:',
        position: { x: 20, y: 261.92 },
        width: 50,
        height: 7.36,
        rotate: 0,
        alignment: 'left',
        verticalAlignment: 'bottom',
        fontSize: 14,
        lineHeight: 1,
        characterSpacing: 0,
        fontColor: '#000000',
        backgroundColor: '',
        opacity: 1,
        readOnly: true,
        fontName: 'NotoSerifJP-Regular',
      },
      creatorName: {
        type: 'readOnlyText',
        icon: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-type"><polyline points="4 7 4 4 20 4 20 7"/><line x1="9" x2="15" y1="20" y2="20"/><line x1="12" x2="12" y1="4" y2="20"/></svg>',
        content: 'Creator name',
        position: { x: 20, y: 269.59 },
        width: 50,
        height: 7.36,
        rotate: 0,
        alignment: 'left',
        verticalAlignment: 'bottom',
        fontSize: 14,
        lineHeight: 1,
        characterSpacing: 0,
        fontColor: '#000000',
        backgroundColor: '',
        opacity: 1,
        readOnly: true,
        fontName: 'NotoSerifJP-Regular',
      },
      pageNumber: {
        type: 'readOnlyText',
        icon: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-type"><polyline points="4 7 4 4 20 4 20 7"/><line x1="9" x2="15" y1="20" y2="20"/><line x1="12" x2="12" y1="4" y2="20"/></svg>',
        content: 'Page 2 from 5',
        position: { x: 155, y: 271.23 },
        width: 35,
        height: 5.769999999999982,
        rotate: 0,
        alignment: 'left',
        verticalAlignment: 'bottom',
        fontSize: 12,
        lineHeight: 1,
        characterSpacing: 0,
        fontColor: '#000000',
        backgroundColor: '',
        opacity: 1,
        readOnly: true,
        fontName: 'NotoSerifJP-Regular',
      },
      summaryLabel: {
        type: 'readOnlyText',
        icon: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-type"><polyline points="4 7 4 4 20 4 20 7"/><line x1="9" x2="15" y1="20" y2="20"/><line x1="12" x2="12" y1="4" y2="20"/></svg>',
        content: 'Summary',
        position: { x: 20, y: 149.91 },
        width: 170,
        height: 10,
        rotate: 0,
        alignment: 'left',
        verticalAlignment: 'top',
        fontSize: 18,
        lineHeight: 1,
        characterSpacing: 0,
        fontColor: '#000000',
        backgroundColor: '',
        opacity: 1,
        readOnly: true,
      },
      summaryConfigurationTable: {
        type: 'table',
        position: { x: 20, y: 162.65 },
        width: 170,
        height: 43.75920000000001,
        content: '[["Configuration name 1","$123"],["",""]]',
        showHead: true,
        head: ['Configuration name', 'Total'],
        headWidthPercentages: [67.25613086103682, 32.74386913896316],
        fontName: 'NotoSerifJP-Regular',
        tableStyles: { borderWidth: 0, borderColor: '#000000' },
        headStyles: {
          fontName: 'NotoSerifJP-Regular',
          fontSize: 13,
          characterSpacing: 0,
          alignment: 'center',
          verticalAlignment: 'middle',
          lineHeight: 1,
          fontColor: '#2f40d6',
          borderColor: '#2f40d6',
          backgroundColor: '#d7daf7',
          borderWidth: { top: 0.2, right: 0.2, bottom: 0.2, left: 0.2 },
          padding: { top: 5, right: 5, bottom: 5, left: 5 },
        },
        bodyStyles: {
          fontName: 'NotoSerifJP-Regular',
          fontSize: 13,
          characterSpacing: 0,
          alignment: 'center',
          verticalAlignment: 'middle',
          lineHeight: 1,
          fontColor: '#000000',
          borderColor: '#000000',
          backgroundColor: '',
          alternateBackgroundColor: '',
          borderWidth: { top: 0.2, right: 0.2, bottom: 0.2, left: 0.2 },
          padding: { top: 5, right: 5, bottom: 5, left: 5 },
        },
        columnStyles: { alignment: { '0': 'center', '1': 'center' } },
      },
      totalPriceLabel: {
        type: 'readOnlyText',
        icon: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-type"><polyline points="4 7 4 4 20 4 20 7"/><line x1="9" x2="15" y1="20" y2="20"/><line x1="12" x2="12" y1="4" y2="20"/></svg>',
        content: 'Total price:',
        position: { x: 20.53, y: 217.91 },
        width: 55.85,
        height: 10,
        rotate: 0,
        alignment: 'left',
        verticalAlignment: 'top',
        fontSize: 18,
        lineHeight: 1,
        characterSpacing: 0,
        fontColor: '#000000',
        backgroundColor: '',
        opacity: 1,
        readOnly: true,
        fontName: 'NotoSerifJP-Regular',
      },
      totalPrice: {
        type: 'readOnlyText',
        icon: '<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="lucide lucide-type"><polyline points="4 7 4 4 20 4 20 7"/><line x1="9" x2="15" y1="20" y2="20"/><line x1="12" x2="12" y1="4" y2="20"/></svg>',
        content: '282 932 PLN',
        position: { x: 134.42, y: 217.91 },
        width: 55.58,
        height: 10,
        rotate: 0,
        alignment: 'right',
        verticalAlignment: 'top',
        fontSize: 18,
        lineHeight: 1,
        characterSpacing: 0,
        fontColor: '#000000',
        backgroundColor: '',
        opacity: 1,
        readOnly: true,
        fontName: 'NotoSerifJP-Regular',
      },
    },
  ],
  basePdf: { width: 210, height: 297, padding: [20, 20, 20, 20] },
  pdfmeVersion: '4.0.0',
};

export default template;
